abbreviations = {
  gen: "Genesis",
  exo: "Exodus",
  lev: "Leviticus",
  num: "Numbers",
  deu: "Deuteronomy",
  jos: "Joshua",
  jdg: "Judges",
  rut: "Ruth",
  sa1: "1 Samuel",
  sa2: "2 Samuel",
  kg1: "1 Kings",
  kg2: "2 Kings",
  ch1: "1 Chronicles",
  ch2: "2 Chronicles",
  ezr: "Ezra",
  neh: "Nehemiah",
  est: "Esther",
  job: "Job",
  psa: "Psalms",
  pro: "Proverbs",
  ecc: "Ecclesiastes",
  sol: "Song of Solomon",
  isa: "Isaiah",
  jer: "Jeremiah",
  lam: "Lamentations",
  eze: "Ezekiel",
  dan: "Daniel",
  hos: "Hosea",
  joe: "Joel",
  amo: "Amos",
  oba: "Obadiah",
  jon: "Jonah",
  mic: "Micah",
  nah: "Nahum",
  hab: "Habakkuk",
  zep: "Zephaniah",
  hag: "Haggai",
  zac: "Zechariah",
  mal: "Malachi",
  es1: "1 Esdras",
  es2: "2 Esdras",
  tob: "Tobias",
  jdt: "Judith",
  aes: "Additions to Esther",
  wis: "Wisdom",
  bar: "Baruch",
  epj: "Epistle of Jeremiah",
  sus: "Susanna",
  bel: "Bel and the Dragon",
  man: "Prayer of Manasseh",
  ma1: "1 Macabees",
  ma2: "2 Macabees",
  ma3: "3 Macabees",
  ma4: "4 Macabees",
  sir: "Sirach",
  aza: "Prayer of Azariah",
  lao: "Laodiceans",
  jsb: "Joshua B",
  jsa: "Joshua A",
  jdb: "Judges B",
  jda: "Judges A",
  toa: "Tobit BA",
  tos: "Tobit S",
  pss: "Psalms of Solomon",
  bet: "Bel and the Dragon Th",
  dat: "Daniel Th",
  sut: "Susanna Th",
  ode: "Odes",
  mat: "Matthew",
  mar: "Mark",
  luk: "Luke",
  joh: "John",
  act: "Acts",
  rom: "Romans",
  co1: "1 Corinthians",
  co2: "2 Corinthians",
  gal: "Galatians",
  eph: "Ephesians",
  phi: "Philippians",
  col: "Colossians",
  th1: "1 Thessalonians",
  th2: "2 Thessalonians",
  ti1: "1 Timothy",
  ti2: "2 Timothy",
  tit: "Titus",
  plm: "Philemon",
  heb: "Hebrews",
  jam: "James",
  pe1: "1 Peter",
  pe2: "2 Peter",
  jo1: "1 John",
  jo2: "2 John",
  jo3: "3 John",
  jde: "Jude",
  rev: "Revelation"
}
